properties:
    tempPath: C:\Users\Administrator\Desktop\tempFolder
    companyName: PhillipsCompany
    companyId: 12341234123412341234123412341234
    dataPath: C:\Users\Administrator\Desktop\dataFolder
    originalResumesPath: C:\Users\Administrator\Desktop
